feat: improve setup

diff --git a/.github/actions/do-auto-format/action.yaml b/.github/actions/do-auto-format/action.yaml
--- a/.github/actions/do-auto-format/action.yaml
+++ b/.github/actions/do-auto-format/action.yaml
@@ -1,4 +1,4 @@
-# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
+# SPDX-FileCopyrightText: Copyright 2020-2026, Contributors to Tyrannosaurus
 # SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
 # SPDX-License-Identifier: Apache-2.0
 
@@ -16,7 +16,9 @@ inputs:
       For a PR, this is probably the base commit.
   push:
     required: true
-    description: Push changes; otherwise, errors if there were changes.
+    description: >-
+      Push changes; otherwise, errors if there were changes.
+      Literal 'true' or 'false'.
 
 outputs:
   auto-fix:
@@ -31,6 +33,13 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        if [[ ! '${{ inputs.push }}' =~ ^(?:true|false)$ ]]; then
+          printf >&2 "ERROR: push is not true|false: '%s'.\n" '${{ inputs.push }}'
+          exit 2
+        fi
     - name: Configure Git
       shell: bash
       run: |
@@ -51,7 +60,7 @@ runs:
     - uses: astral-sh/setup-uv@v7
     - shell: bash
       run: |
-        uv sync --locked --only-group precommit
+        uv sync --locked --only-group git-hooks
     - name: Sanity-check that there are no local changes
       shell: bash
       run: |
@@ -109,12 +118,13 @@ runs:
       run: |
         untracked="$(git ls-files --others --exclude-standard)"
         if [[ -n "$untracked" ]]; then
-          printf "\n\nWARNING: Found unexpected untracked files: (((\n%s\n)))\n\n" "$untracked"
-        fi
-        if [[ '${{ inputs.push }}' == true ]]; then
+          printf >&2 "\n\nERROR: Found unexpected untracked files! (((\n%s\n)))\n\n" "$untracked"
+          exit 1
+        elif [[ '${{ inputs.push }}' == true ]]; then
           # NOTE: Let it fail if another commit was added!
           git push
+          printf "Success. No changes needed.\n"
         else
-          printf "Changes are needed, as shown above.\n"
+          printf "Failure. Changes are needed, as shown above.\n"
           exit 1
         fi
diff --git a/.github/actions/sync-repo-info/action.yaml b/.github/actions/sync-repo-info/action.yaml
--- a/.github/actions/sync-repo-info/action.yaml
+++ b/.github/actions/sync-repo-info/action.yaml
@@ -1,4 +1,4 @@
-# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
+# SPDX-FileCopyrightText: Copyright 2020-2026, Contributors to Tyrannosaurus
 # SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
 # SPDX-License-Identifier: Apache-2.0
 
@@ -21,7 +21,7 @@ runs:
         labels_blob=$(gh api "/repos/$GITHUB_REPOSITORY/labels" --jq '.[].name')
         # Loop over the labels and delete them
         while IFS= read -r label; do
-          printf "Deleting label: //%s//\n" "$label"
+          printf "Deleting label: '%s'.\n" "$label"
           gh api --method DELETE "/repos/$GITHUB_REPOSITORY/labels/$label"
         done <<< "$labels_blob"
     - name: Wait for changes to be made
@@ -32,7 +32,7 @@ runs:
         sleep 15
         labels_blob=$(gh api "/repos/$GITHUB_REPOSITORY/labels" --jq '.[].name')
         if (( $(wc -l <<< "$labels_blob") > 0 )); then
-          printf "[ERROR] Labels were not deleted: %s.\n" "$labels_blob"
+          printf >&2 "ERROR: Labels were not deleted: (((\n%s\n)))\n\n" "$labels_blob"
           exit 1
         fi
     - name: Create new labels
@@ -65,7 +65,7 @@ runs:
         homepage=$(yq eval '.homepage' "$SETTINGS_PATH")
         topics=$(yq eval '.topics | join(",")' "$SETTINGS_PATH")
         # Update the repo metadata.
-        gh repo edit $GITHUB_REPOSITORY \
+        gh repo edit ${{ github.repository }} \
           --description "$description" \
           --homepage "$homepage" \
           --add-topic "$topics"
